export const CHANGE_TEXT = "CHANGE_TEXT";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const SUBTRACT_QUANTITY = "SUBTRACT_QUANTITY";
export const REMOVE_CART = "REMOVE_CART";
export const ADD_DELIVERY = "ADD_DELIVERY";
export const ADD_PAY_METHOD = "ADD_PAY_METHOD";
